// Quotes shown on the login screen. One is drawn at random when the app
// launches and stays fixed for that session, so it never changes under you
// mid-login but is different every time you open WorkTrack Pro.

export const QUOTES = [
  { text: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney' },
  { text: "Don't watch the clock; do what it does. Keep going.", author: 'Sam Levenson' },
  { text: 'Either you run the day or the day runs you.', author: 'Jim Rohn' },
  { text: 'Well done is better than well said.', author: 'Benjamin Franklin' },
  { text: 'Success is the sum of small efforts repeated day in and day out.', author: 'Robert Collier' },
  { text: 'It always seems impossible until it is done.', author: 'Nelson Mandela' },
  { text: 'Quality is not an act, it is a habit.', author: 'Aristotle' },
  { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
  { text: 'Action is the foundational key to all success.', author: 'Pablo Picasso' },
  { text: 'Simplicity is the ultimate sophistication.', author: 'Leonardo da Vinci' },
  { text: 'Whether you think you can or you think you can’t, you’re right.', author: 'Henry Ford' },
  { text: 'Great things are done by a series of small things brought together.', author: 'Vincent van Gogh' },
  { text: 'Amateurs sit and wait for inspiration. The rest of us just get up and go to work.', author: 'Stephen King' },
  { text: 'Perfection is not attainable, but if we chase perfection we can catch excellence.', author: 'Vince Lombardi' },
  { text: 'You don’t have to be great to start, but you have to start to be great.', author: 'Zig Ziglar' },
  { text: 'The future depends on what you do today.', author: 'Mahatma Gandhi' },
  { text: 'Discipline is the bridge between goals and accomplishment.', author: 'Jim Rohn' },
  { text: 'Hard work beats talent when talent doesn’t work hard.', author: 'Tim Notke' },
  { text: 'Opportunities don’t happen. You create them.', author: 'Chris Grosser' },
  { text: 'Do the hard jobs first. The easy jobs will take care of themselves.', author: 'Dale Carnegie' },
  { text: 'Start where you are. Use what you have. Do what you can.', author: 'Arthur Ashe' },
  { text: 'It’s not that I’m so smart, it’s just that I stay with problems longer.', author: 'Albert Einstein' },
  { text: 'A year from now you may wish you had started today.', author: 'Karen Lamb' },
  { text: 'People who are crazy enough to think they can change the world are the ones who do.', author: 'Rob Siltanen' },
  { text: 'Never confuse motion with action.', author: 'Ernest Hemingway' },
  { text: 'Courage is what it takes to stand up and speak; also to sit down and listen.', author: 'Winston Churchill' },
  { text: 'If you are working on something that you really care about, you don’t have to be pushed.', author: 'Steve Jobs' },
  { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
  { text: 'We are what we repeatedly do. Excellence, then, is not an act but a habit.', author: 'Will Durant' },
  { text: 'Nothing will work unless you do.', author: 'Maya Angelou' },
  { text: 'Setting goals is the first step in turning the invisible into the visible.', author: 'Tony Robbins' },
  { text: 'You miss 100% of the shots you don’t take.', author: 'Wayne Gretzky' },
  { text: 'Everything you’ve ever wanted is on the other side of fear.', author: 'George Addair' },
  { text: 'Done is better than perfect.', author: 'Sheryl Sandberg' },
  { text: 'The best way to predict the future is to create it.', author: 'Peter Drucker' },
  { text: 'What gets measured gets managed.', author: 'Peter Drucker' },
  { text: 'Efficiency is doing things right; effectiveness is doing the right things.', author: 'Peter Drucker' },
  { text: 'Time is the scarcest resource; unless it is managed, nothing else can be managed.', author: 'Peter Drucker' },
  { text: 'It is not enough to be busy. The question is: what are we busy about?', author: 'Henry David Thoreau' },
  { text: 'Lost time is never found again.', author: 'Benjamin Franklin' },
  { text: 'You may delay, but time will not.', author: 'Benjamin Franklin' },
  { text: 'Ordinary people think merely of spending time. Great people think of using it.', author: 'Arthur Schopenhauer' },
  { text: 'The bad news is time flies. The good news is you’re the pilot.', author: 'Michael Altshuler' },
  { text: 'Until we can manage time, we can manage nothing else.', author: 'Peter Drucker' },
  { text: 'Take care of the minutes and the hours will take care of themselves.', author: 'Lord Chesterfield' },
  { text: 'Better three hours too soon than a minute too late.', author: 'William Shakespeare' },
  { text: 'Punctuality is the politeness of kings.', author: 'Louis XVIII' },
  { text: 'How we spend our days is, of course, how we spend our lives.', author: 'Annie Dillard' },
  { text: 'Yesterday is gone. Tomorrow has not yet come. We have only today.', author: 'Mother Teresa' },
  { text: 'Don’t count the days, make the days count.', author: 'Muhammad Ali' },
  { text: 'Excellence is never an accident.', author: 'Aristotle' },
  { text: 'Whatever you are, be a good one.', author: 'Abraham Lincoln' },
  { text: 'The reward for work well done is the opportunity to do more.', author: 'Jonas Salk' },
  { text: 'Talent wins games, but teamwork wins championships.', author: 'Michael Jordan' },
  { text: 'Alone we can do so little; together we can do so much.', author: 'Helen Keller' },
  { text: 'Coming together is a beginning, staying together is progress, working together is success.', author: 'Henry Ford' },
  { text: 'If everyone is moving forward together, then success takes care of itself.', author: 'Henry Ford' },
  { text: 'None of us is as smart as all of us.', author: 'Ken Blanchard' },
  { text: 'Trust is the glue of life. It’s the foundational principle that holds all relationships.', author: 'Stephen Covey' },
  { text: 'The main thing is to keep the main thing the main thing.', author: 'Stephen Covey' },
  { text: 'Most of us spend too much time on what is urgent and not enough on what is important.', author: 'Stephen Covey' },
  { text: 'Motivation is what gets you started. Habit is what keeps you going.', author: 'Jim Rohn' },
  { text: 'Success is nothing more than a few simple disciplines, practised every day.', author: 'Jim Rohn' },
  { text: 'You do not rise to the level of your goals. You fall to the level of your systems.', author: 'James Clear' },
  { text: 'Every action you take is a vote for the type of person you wish to become.', author: 'James Clear' },
  { text: 'Small habits don’t add up. They compound.', author: 'James Clear' },
  { text: 'The man who moves a mountain begins by carrying away small stones.', author: 'Confucius' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { text: 'Wherever you go, go with all your heart.', author: 'Confucius' },
  { text: 'Knowing is not enough; we must apply. Willing is not enough; we must do.', author: 'Johann Wolfgang von Goethe' },
  { text: 'Things which matter most must never be at the mercy of things which matter least.', author: 'Johann Wolfgang von Goethe' },
  { text: 'Patience and perseverance have a magical effect before which difficulties disappear.', author: 'John Quincy Adams' },
  { text: 'Energy and persistence conquer all things.', author: 'Benjamin Franklin' },
  { text: 'Fall seven times, stand up eight.', author: 'Japanese proverb' },
  { text: 'A river cuts through rock not because of its power but its persistence.', author: 'Jim Watkins' },
  { text: 'Continuous improvement is better than delayed perfection.', author: 'Mark Twain' },
  { text: 'If you want to go fast, go alone. If you want to go far, go together.', author: 'African proverb' },
  { text: 'The expert in anything was once a beginner.', author: 'Helen Hayes' },
  { text: 'Be so good they can’t ignore you.', author: 'Steve Martin' },
  { text: 'Work hard in silence; let success make the noise.', author: 'Frank Ocean' },
  { text: 'There is no substitute for hard work.', author: 'Thomas Edison' },
  { text: 'Genius is one percent inspiration and ninety-nine percent perspiration.', author: 'Thomas Edison' },
  { text: 'Our greatest weakness lies in giving up.', author: 'Thomas Edison' },
  { text: 'I never dreamed about success, I worked for it.', author: 'Estée Lauder' },
  { text: 'Doubt kills more dreams than failure ever will.', author: 'Suzy Kassem' },
  { text: 'The harder you work for something, the greater you’ll feel when you achieve it.', author: 'Anonymous' },
  { text: 'Dream big. Start small. Act now.', author: 'Robin Sharma' },
  { text: 'Change is the end result of all true learning.', author: 'Leo Buscaglia' },
  { text: 'Learning never exhausts the mind.', author: 'Leonardo da Vinci' },
  { text: 'An investment in knowledge pays the best interest.', author: 'Benjamin Franklin' },
  { text: 'The beautiful thing about learning is that no one can take it away from you.', author: 'B.B. King' },
  { text: 'Strive not to be a success, but rather to be of value.', author: 'Albert Einstein' },
  { text: 'In the middle of difficulty lies opportunity.', author: 'Albert Einstein' },
  { text: 'The only limit to our realisation of tomorrow is our doubts of today.', author: 'Franklin D. Roosevelt' },
  { text: 'Happiness is not something ready made. It comes from your own actions.', author: 'Dalai Lama' },
  { text: 'Do what you can, with what you have, where you are.', author: 'Theodore Roosevelt' },
  { text: 'Believe you can and you’re halfway there.', author: 'Theodore Roosevelt' },
  { text: 'Nothing worth having comes easy.', author: 'Theodore Roosevelt' },
  { text: 'Keep your eyes on the stars, and your feet on the ground.', author: 'Theodore Roosevelt' },
  { text: 'A goal without a plan is just a wish.', author: 'Antoine de Saint-Exupéry' },
  { text: 'Perfection is achieved when there is nothing left to take away.', author: 'Antoine de Saint-Exupéry' },
  { text: 'Make each day your masterpiece.', author: 'John Wooden' },
  { text: 'It’s what you learn after you know it all that counts.', author: 'John Wooden' },
  { text: 'Failure is not fatal, but failure to change might be.', author: 'John Wooden' },
  { text: 'If you’re going through hell, keep going.', author: 'Winston Churchill' },
  { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill' },
  { text: 'Attitude is a little thing that makes a big difference.', author: 'Winston Churchill' },
  { text: 'You get in life what you have the courage to ask for.', author: 'Oprah Winfrey' },
  { text: 'Turn your wounds into wisdom.', author: 'Oprah Winfrey' },
  { text: 'Nothing is impossible. The word itself says “I’m possible”.', author: 'Audrey Hepburn' },
  { text: 'Act as if what you do makes a difference. It does.', author: 'William James' },
  { text: 'The greatest weapon against stress is our ability to choose one thought over another.', author: 'William James' },
  { text: 'Life is 10% what happens to us and 90% how we react to it.', author: 'Charles R. Swindoll' },
  { text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis' },
  { text: 'Integrity is doing the right thing, even when no one is watching.', author: 'C.S. Lewis' },
  { text: 'Hardships often prepare ordinary people for an extraordinary destiny.', author: 'C.S. Lewis' },
  { text: 'What we achieve inwardly will change outer reality.', author: 'Plutarch' },
  { text: 'The journey of a thousand miles begins with one step.', author: 'Lao Tzu' },
  { text: 'Nature does not hurry, yet everything is accomplished.', author: 'Lao Tzu' },
  { text: 'When I let go of what I am, I become what I might be.', author: 'Lao Tzu' },
  { text: 'He who has a why to live can bear almost any how.', author: 'Friedrich Nietzsche' },
  { text: 'That which does not kill us makes us stronger.', author: 'Friedrich Nietzsche' },
  { text: 'Do not wait; the time will never be “just right”.', author: 'Napoleon Hill' },
  { text: 'Patience, persistence and perspiration make an unbeatable combination for success.', author: 'Napoleon Hill' },
  { text: 'Whatever the mind can conceive and believe, it can achieve.', author: 'Napoleon Hill' },
  { text: 'The only person you are destined to become is the person you decide to be.', author: 'Ralph Waldo Emerson' },
  { text: 'Do not go where the path may lead, go instead where there is no path and leave a trail.', author: 'Ralph Waldo Emerson' },
  { text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson' },
  { text: 'The mind is everything. What you think you become.', author: 'Buddha' },
  { text: 'No one saves us but ourselves. No one can and no one may.', author: 'Buddha' },
  { text: 'Arise, awake, and stop not till the goal is reached.', author: 'Swami Vivekananda' },
  { text: 'Take up one idea. Make that one idea your life.', author: 'Swami Vivekananda' },
  { text: 'You have to dream before your dreams can come true.', author: 'A.P.J. Abdul Kalam' },
  { text: 'If you want to shine like a sun, first burn like a sun.', author: 'A.P.J. Abdul Kalam' },
  { text: 'Excellence is a continuous process and not an accident.', author: 'A.P.J. Abdul Kalam' },
  { text: 'Great dreams of great dreamers are always transcended.', author: 'A.P.J. Abdul Kalam' },
  { text: 'Be the change that you wish to see in the world.', author: 'Mahatma Gandhi' },
  { text: 'Satisfaction lies in the effort, not in the attainment.', author: 'Mahatma Gandhi' },
  { text: 'Live as if you were to die tomorrow. Learn as if you were to live forever.', author: 'Mahatma Gandhi' },
  { text: 'A person who never made a mistake never tried anything new.', author: 'Albert Einstein' },
  { text: 'Try not to become a person of success, but rather a person of value.', author: 'Albert Einstein' },
  { text: 'Character cannot be developed in ease and quiet.', author: 'Helen Keller' },
  { text: 'Optimism is the faith that leads to achievement.', author: 'Helen Keller' },
  { text: 'Keep your face always toward the sunshine and shadows will fall behind you.', author: 'Walt Whitman' },
  { text: 'We generate fears while we sit. We overcome them by action.', author: 'Dr. Henry Link' },
  { text: 'Begin anywhere.', author: 'John Cage' },
  { text: 'Slow is smooth, and smooth is fast.', author: 'Navy SEAL adage' },
  { text: 'Discipline equals freedom.', author: 'Jocko Willink' },
  { text: 'Focus is a matter of deciding what things you’re not going to do.', author: 'John Carmack' },
  { text: 'The best time to plant a tree was twenty years ago. The second best time is now.', author: 'Chinese proverb' },
  { text: 'A smooth sea never made a skilled sailor.', author: 'Franklin D. Roosevelt' },
  { text: 'Tough times never last, but tough people do.', author: 'Robert H. Schuller' },
  { text: 'Try again. Fail again. Fail better.', author: 'Samuel Beckett' },
  { text: 'There are no shortcuts to any place worth going.', author: 'Beverly Sills' },
]

// Picked once per app launch — the module only evaluates when the renderer loads.
export const LAUNCH_QUOTE = QUOTES[Math.floor(Math.random() * QUOTES.length)]
